In [1]:
import numpy as np
import pandas as pd


In [33]:
df = pd.read_csv("../datasets/daraz_dataset.csv")
df.shape
df.columns
df.dtypes

features = ["Age", "Quantity", "UnitPrice", "DiscountPercent"]
target = "TotalAmount"

# Super features store garne X , target store garne Y
X = df[features]
y = df["TotalAmount"]

type(X)
type(y)

X = X.to_numpy()
y = y.to_numpy()

type(X)
type(y)

# X.shape
# X.ndim
# X.dtype

X[0]
X[:, 0]
X[:, 3]
print(X[X[:, 0] > 30])
print(np.min(X[:, 0]))

[[   52     2 33418    20]
 [   31     2 46053    15]
 [   42     5 17635     0]
 ...
 [   39     4 30055    20]
 [   48     3 47942    20]
 [   35     4  5707     5]]
18


In [8]:
# Scalar and Vector
age = np.array([10, 20, 30]) 
roll = np.array([11, 22, 33])
# In AI, this is vector and in python, this is numpy array
print(age) 
print(roll)

# Matrix is the collection of vectors
matrix = np.array([
    [10, 20, 30],
    [11, 22, 33]
])
print(matrix)

[10 20 30]
[11 22 33]
[[10 20 30]
 [11 22 33]]


In [11]:
# student_data_row1 = np.array([12, 90]) # (studyhours, attendance
# student_data_row2 = np.array([14, 80])
# student_data_row3 = np.array([16, 50])

#Better way to represent above data
student_data = ([
    [12, 90],
    [14, 80],
    [16, 50]
])

weights = np.array([10, 2])

prediction = np.dot(student_data, weights)
print(prediction)


[300 300 260]
