In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    "price" : [100, 200, 300]
})
print(type(df["price"].values))

<class 'numpy.ndarray'>


In [2]:
import numpy as np

In [13]:
salary_array = np.array([1000, 2000, 3000])
print(type(salary_array))
new_salary_array = salary_array + 1
new_salary_array


<class 'numpy.ndarray'>


array([1001, 2001, 3001])

In [33]:
salary_array = np.array([1000, 2000, 3000])
data = np.array([
    [10, 1000],
        [20, 2000],
        [30, 3000],
         [40, 4000],
        [50, 5000],
        [60, 6000],
])
print(data.ndim)
print(data.shape)
print(data.size)
print(data[0,1]) # getting 1000
print(data[0:3, ])
print(data[3:5])
print(data[:,0])

2
(6, 2)
12
1000
[[  10 1000]
 [  20 2000]
 [  30 3000]]
[[  40 4000]
 [  50 5000]]
[10 20 30 40 50 60]


In [10]:
# Vectorization
numbers = np.array([1, 2, 3, 4, 5])
# 10, 10, 10, 10, 10 [1, 2, 3, 4, 5] --> 1 * 10, 2 * 10, 3 * 10, 4 * 10, 5 * 10 (Behind the scene) => this is done in broadcasting

result = numbers * 10 
# result
result[(result > 30) & (result < 50)] # Filtering in vectorization
# result[result > 30] # array([False, False, False,  True,  True])
# print(result)
            
                

array([40])

In [11]:
# Vectorization
price = np.array([100, 200, 300])
quantity = np.array([2, 4, 6])
total_cost = price * quantity
total_cost

array([ 200,  800, 1800])

In [14]:
# Array Reshaping : change the shape of an array according to our need
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2,3)
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr2.shape
# arr2.reshape(1, 6)
arr2.reshape(-1) # Use -1 to automatically infer one dimension:
arr.reshape(3, -1) # (-1) NumPy automatically calculates the missing dimension


array([[1, 2],
       [3, 4],
       [5, 6]])